version: "2.14.2"
services:
  nasa-client:
    container_name: frontend
    build: ./client
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - nasa-server
  nasa-server:
    container_name: api
    build: ./server
    command: npm run watch
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/src/test
